package sweet.framework.repository.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.ID
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.NAME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.AGE
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CREATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SALARY
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    private Long salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.ID
     *
     * @return the value of User.ID
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.ID
     *
     * @param id the value for User.ID
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.NAME
     *
     * @return the value of User.NAME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.NAME
     *
     * @param name the value for User.NAME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.AGE
     *
     * @return the value of User.AGE
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.AGE
     *
     * @param age the value for User.AGE
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CREATE_TIME
     *
     * @return the value of User.CREATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CREATE_TIME
     *
     * @param createTime the value for User.CREATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UPDATE_TIME
     *
     * @return the value of User.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UPDATE_TIME
     *
     * @param updateTime the value for User.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SALARY
     *
     * @return the value of User.SALARY
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public Long getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SALARY
     *
     * @param salary the value for User.SALARY
     *
     * @mbg.generated Mon Jan 02 18:05:12 HKT 2017
     */
    public void setSalary(Long salary) {
        this.salary = salary;
    }
}